import { Post, Community, User } from './types';

// Mock Communities
export const mockCommunities: Community[] = [
  {
    id: '1',
    name: 'programming',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=programming',
    description: 'Computer Programming',
    members: 5243000,
    createdAt: '2008-01-25T00:00:00.000Z',
  },
  {
    id: '2',
    name: 'webdev',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=webdev',
    description: 'Web Development',
    members: 934000,
    createdAt: '2009-03-15T00:00:00.000Z',
  },
  {
    id: '3',
    name: 'nextjs',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=nextjs',
    description: 'The React Framework',
    members: 324000,
    createdAt: '2016-10-25T00:00:00.000Z',
  },
  {
    id: '4',
    name: 'reactjs',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=reactjs',
    description: 'A JavaScript library for building user interfaces',
    members: 842000,
    createdAt: '2013-05-29T00:00:00.000Z',
  },
  {
    id: '5',
    name: 'tailwindcss',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development',
    members: 254000,
    createdAt: '2017-11-01T00:00:00.000Z',
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    username: 'dev_guru',
    karma: 15432,
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=dev_guru',
  },
  {
    id: '2',
    username: 'code_ninja',
    karma: 8765,
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=code_ninja',
  },
  {
    id: '3',
    username: 'webmaster',
    karma: 5421,
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=webmaster',
  },
  {
    id: '4',
    username: 'frontend_fan',
    karma: 3254,
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=frontend_fan',
  },
  {
    id: '5',
    username: 'ui_designer',
    karma: 9876,
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=ui_designer',
  },
];

// Mock Posts
export const mockPosts: Post[] = [
  {
    id: '1',
    title: 'Introducing the Next.js App Router',
    content: "The App Router is a new paradigm for building applications using React's latest features. Today, we're excited to share that the App Router is stable and ready for production.",
    contentType: 'text',
    author: mockUsers[0],
    community: mockCommunities[2],
    votes: 3245,
    commentCount: 342,
    createdAt: '2023-05-04T10:30:00.000Z',
    tags: ['Next.js', 'React', 'Frontend'],
  },
  {
    id: '2',
    title: 'This new VS Code feature is a game changer for developers',
    content: 'https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    contentType: 'image',
    author: mockUsers[1],
    community: mockCommunities[0],
    votes: 1876,
    commentCount: 156,
    createdAt: '2023-05-03T14:20:00.000Z',
    tags: ['VS Code', 'Tools', 'Productivity'],
  },
  {
    id: '3',
    title: 'TailwindCSS v4 alpha is now available!',
    content: 'https://tailwindcss.com/blog/tailwindcss-v4-alpha',
    contentType: 'link',
    author: mockUsers[4],
    community: mockCommunities[4],
    votes: 2543,
    commentCount: 211,
    createdAt: '2023-05-02T08:15:00.000Z',
    tags: ['Tailwind', 'CSS', 'Frontend'],
  },
  {
    id: '4',
    title: 'React Server Components explained simply',
    content: "React Server Components (RSC) are a new paradigm that enables rendering React components on the server. Unlike traditional SSR, RSCs don't require hydration on the client, reducing JavaScript shipped to the browser. This leads to improved performance, especially for content-heavy websites.",
    contentType: 'text',
    author: mockUsers[3],
    community: mockCommunities[3],
    votes: 932,
    commentCount: 78,
    createdAt: '2023-05-01T11:45:00.000Z',
    tags: ['React', 'Server Components', 'Performance'],
  },
  {
    id: '5',
    title: 'The state of Web Development in 2023 [Survey Results]',
    content: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    contentType: 'image',
    author: mockUsers[2],
    community: mockCommunities[1],
    votes: 1654,
    commentCount: 123,
    createdAt: '2023-04-30T09:30:00.000Z',
    tags: ['Web Development', 'Survey', 'Trends'],
  },
  {
    id: '6',
    title: "Understanding the CSS 'aspect-ratio' property",
    content: "The 'aspect-ratio' property in CSS is incredibly useful for maintaining the proportions of elements. It's particularly handy for responsive design, as it allows you to specify a width/height ratio that the browser will maintain regardless of the viewport size. This is much cleaner than older hacks using percentage padding.",
    contentType: 'text',
    author: mockUsers[4],
    community: mockCommunities[1],
    votes: 765,
    commentCount: 45,
    createdAt: '2023-04-29T16:20:00.000Z',
    tags: ['CSS', 'Web Design', 'Responsive'],
  },
  {
    id: '7',
    title: 'GitHub Copilot X: The AI-powered developer experience',
    content: 'https://github.blog/2023-03-22-github-copilot-x-the-ai-powered-developer-experience/',
    contentType: 'link',
    author: mockUsers[0],
    community: mockCommunities[0],
    votes: 2198,
    commentCount: 198,
    createdAt: '2023-04-28T13:10:00.000Z',
    tags: ['GitHub', 'AI', 'Developer Tools'],
  },
];